# Generated by Django 5.1.6 on 2025-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auction_user_watchlist_bid_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="auctions/images"),
        ),
    ]
