# Generated by Django 5.1.6 on 2025-02-27 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_category_remove_auction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auctions",
                to="auctions.category",
            ),
        ),
    ]
