# Generated by Django 5.1.6 on 2025-03-20 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripnavigator", "0006_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelplan",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="travelplan",
            name="category",
            field=models.CharField(
                choices=[
                    ("family", "Family Trip"),
                    ("romantic", "Romantic Holiday"),
                    ("adventure", "Adventure Trip"),
                    ("cultural", "Cultural Journey"),
                    ("wellness", "Wellness & Spa"),
                    ("road", "Road Trip"),
                    ("budget", "Budget Travel"),
                    ("luxury", "Luxury Escape"),
                    ("nature", "Nature & Outdoor"),
                    ("historical", "Historical Tour"),
                    ("other", "Other"),
                ],
                default="none",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="travelplan",
            name="destination",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="travelplan",
            name="end_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="travelplan",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="trip_planner_images/"
            ),
        ),
        migrations.AddField(
            model_name="travelplan",
            name="start_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TravelPlanShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_email", models.EmailField(max_length=254)),
                ("shared_name", models.CharField(max_length=255)),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "travel_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="tripnavigator.travelplan",
                    ),
                ),
            ],
        ),
    ]
