# Generated by Django 5.1.6 on 2025-03-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripnavigator", "0007_travelplan_budget_travelplan_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelplan",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="travelplan",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
