# Generated by Django 5.1.6 on 2025-03-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripnavigator", "0016_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelplan",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
