# Generated by Django 5.1.6 on 2025-03-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripnavigator", "0020_remove_activity_day_activity_date_delete_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
