# Generated by Django 5.1.6 on 2025-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripnavigator", "0021_activity_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelplan",
            name="hotel_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
