# Generated by Django 5.1.6 on 2025-03-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripnavigator", "0004_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
