# Generated by Django 5.1.6 on 2025-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripnavigator", "0012_alter_travelplan_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelplan",
            name="category",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("family", "Family Trip"),
                    ("romantic", "Romantic Holiday"),
                    ("adventure", "Adventure Trip"),
                    ("cultural", "Cultural Journey"),
                    ("wellness", "Wellness & Spa"),
                    ("road", "Road Trip"),
                    ("budget", "Budget Travel"),
                    ("luxury", "Luxury Escape"),
                    ("nature", "Nature & Outdoor"),
                    ("historical", "Historical Tour"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="travelplan",
            name="destination",
            field=models.CharField(max_length=255),
        ),
    ]
