# Generated by Django 5.1.6 on 2025-03-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripnavigator", "0018_day_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="travel_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="tripnavigator.travelplan",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="travel_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="tripnavigator.travelplan",
            ),
        ),
    ]
