# Generated by Django 5.1.6 on 2025-03-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tripnavigator", "0022_travelplan_hotel_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experiencebooking",
            name="travel_plan",
        ),
        migrations.RemoveField(
            model_name="flightbooking",
            name="travel_plan",
        ),
        migrations.RemoveField(
            model_name="hotelbooking",
            name="travel_plan",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="ExperienceBooking",
        ),
        migrations.DeleteModel(
            name="FlightBooking",
        ),
        migrations.DeleteModel(
            name="HotelBooking",
        ),
    ]
